import { createElement, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Check, ChevronRight, CreditCard, Landmark, ShieldCheck, ShoppingCart, WalletCards } from "lucide-react";
import CheckoutStepper from "../components/CheckoutStepper";
import "./Checkout.css";
import "./CheckoutFlow.css";

const CART_KEY = "mobile_shop_cart";
const DELIVERY_KEY = "mobile_shop_delivery";
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || sessionStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
const formatPrice = (value) => Number(value || 0).toLocaleString("en-IN");
function Payment() {
  const navigate = useNavigate(); const cart = useMemo(() => read(CART_KEY, []), []); const delivery = useMemo(() => read(DELIVERY_KEY, {}), []);
  const [payment, setPayment] = useState("cod"); const [loading, setLoading] = useState(false); const subtotal = cart.reduce((total, item) => total + Number(item.price || 0) * item.quantity, 0);
  const submitOrder = async () => { if (!cart.length || !delivery.customerName || !delivery.phone || !delivery.address || !delivery.city) { navigate("/checkout"); return; } setLoading(true); const methods = { cod: "Cash on Delivery", upi: "UPI", card: "Credit / Debit Card", bank: "Net Banking" }; const order = { customerName: delivery.customerName, phone: delivery.phone, address: delivery.address, items: cart.map(({ productId, name, price, quantity }) => ({ productId, name, price, quantity })), paymentMethod: methods[payment] }; try { const response = await fetch("https://mobile-shop-website-backend.onrender.com/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(order) }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.message || "Unable to place your order"); } const data = await response.json(); const completedOrder = { ...order, orderId: data._id || Date.now(), total: subtotal }; localStorage.removeItem(CART_KEY); localStorage.setItem("lastOrder", JSON.stringify(completedOrder)); sessionStorage.removeItem(DELIVERY_KEY); navigate("/order-success", { state: { order: completedOrder } }); } catch (error) { alert(`Error placing order: ${error.message}\n\nPlease try again or contact support.`); setLoading(false); } };
  if (!cart.length) return <main className="checkout-page-shell"><div className="checkout-page-container"><CheckoutStepper currentStep={3}/><section className="checkout-empty"><ShoppingCart size={42}/><h2>Your cart is empty</h2><p>Add an item before proceeding to payment.</p><button onClick={() => navigate("/mobiles")}>Continue Shopping</button></section></div></main>;
  const options = [{id:"cod",label:"Cash on Delivery",icon:WalletCards},{id:"upi",label:"UPI",icon:CreditCard},{id:"card",label:"Credit / Debit Card",icon:CreditCard},{id:"bank",label:"Net Banking",icon:Landmark}];
  return <main className="checkout-page-shell"><div className="checkout-page-container"><nav className="checkout-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><ChevronRight size={14}/><Link to="/cart">Cart</Link><ChevronRight size={14}/><span>Payment</span></nav><header className="checkout-heading"><h1>Payment</h1><p>Choose your preferred payment method.</p></header><CheckoutStepper currentStep={3}/><div className="checkout-layout"><section className="checkout-card checkout-payment"><h2>Payment Method</h2><div className="checkout-payment-options">{options.map(({id,label,icon:Icon}) => <label className={`checkout-payment-option ${payment === id ? "selected" : ""}`} key={id}><input type="radio" name="payment" value={id} checked={payment === id} onChange={() => setPayment(id)}/>{createElement(Icon, { size: 18 })}<span>{label}</span></label>)}</div><div className="checkout-actions payment-actions"><button className="checkout-back" type="button" onClick={() => navigate("/checkout")}>Back to Delivery</button><button className="checkout-submit" type="button" disabled={loading} onClick={submitOrder}>{loading ? "Processing..." : "Place Order"}</button></div></section><aside className="checkout-summary"><h2>Order Summary</h2><div className="checkout-items">{cart.map((item) => <div className="checkout-item" key={item.productId}><span>{item.name} <em>×{item.quantity}</em></span><strong>₹{formatPrice(Number(item.price) * item.quantity)}</strong></div>)}</div><div className="checkout-summary-row"><span>Shipping</span><strong>Free</strong></div><div className="checkout-divider"/><div className="checkout-total"><span>Grand Total</span><strong>₹{formatPrice(subtotal)}</strong></div><div className="checkout-trust"><div><Check size={15}/><span>Genuine Products</span></div><div><ShieldCheck size={15}/><span>Secure Payments</span></div></div></aside></div></div></main>;
}
export default Payment;
